// Database schema, defined with Drizzle ORM.
//
// Why Drizzle instead of Prisma: Drizzle is pure TypeScript with no native
// binary/engine to download at install, build, or runtime. It talks to
// Postgres through the standard `pg` driver. Migrations are plain, readable
// .sql files under drizzle/ (generated by drizzle-kit, checked into git) that
// anyone -- human or AI -- can read without special tooling. This keeps the
// foundation dependency-light and avoids a class of "works on my machine but
// not in this network/deploy environment" failures.
//
// Edit this file, then run `npm run db:generate` to create a migration and
// `npm run db:migrate` to apply it. See README.md for the full workflow.

import {
  pgTable,
  pgEnum,
  text,
  timestamp,
  boolean,
  integer,
  jsonb,
  varchar,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createId } from "@paralleldrive/cuid2";

const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => createId());

// ---------- Public visitor accounts ----------
// A free account a site visitor creates to unlock full names and contact
// forms on player/coach/club profiles (see getPortalAccount()). Deliberately
// separate from adminUsers below (site staff) and from the accountTypeEnum
// further down (a club/player/coach's own future self-serve login) -- this
// is just "signed up to browse", nothing more.

export const accounts = pgTable("accounts", {
  id: id(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ---------- Admin ----------

export const adminRoleEnum = pgEnum("admin_role", ["OWNER", "STAFF"]);

export const adminUsers = pgTable("admin_users", {
  id: id(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  name: text("name").notNull(),
  role: adminRoleEnum("role").notNull().default("STAFF"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ---------- Shared enums ----------

// Lifecycle status shared by clubs and players moving through the pipeline.
export const recordStatusEnum = pgEnum("record_status", [
  "NEW", // just sourced / submitted, not yet reviewed
  "REVIEWING", // admin is actively looking into this one
  "SHORTLISTED", // good candidate, ready for outreach
  "CONTACTED", // outreach has started
  "IN_TALKS", // active conversation with the club/player
  "PLACED", // successfully matched/placed
  "ARCHIVED", // dead end, not pursuing
]);

export const sourceTypeEnum = pgEnum("source_type", [
  "MANUAL", // entered by hand by an admin
  "AI_SEARCH", // surfaced by the AI-assisted sourcing tool
  "SELF_SUBMITTED", // submitted via a public form by the club/player themselves
]);

export const playerLevelEnum = pgEnum("player_level", [
  "COMMUNITY",
  "AMATEUR_LEAGUE",
  "SEMI_PRO",
  "PROFESSIONAL",
  "INTERNATIONAL",
]);

// ---------- Core marketplace entities ----------

export const clubs = pgTable("clubs", {
  id: id(),
  name: text("name").notNull(),
  country: text("country").notNull(),
  region: text("region"),
  league: text("league"),
  level: playerLevelEnum("level"),
  website: text("website"),
  // Club crest/badge image, uploaded by an admin via Vercel Blob. Shown on
  // the public club card and profile page next to the name; null shows a
  // plain text fallback there.
  crestUrl: text("crest_url"),
  contactName: text("contact_name"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  notes: text("notes"),
  status: recordStatusEnum("status").notNull().default("NEW"),
  source: sourceTypeEnum("source").notNull().default("MANUAL"),
  sourceDetail: text("source_detail"), // e.g. the search query that surfaced this club
  // Whether this record is visible on the public site. Self-submitted
  // clubs start unpublished until a staff member reviews and approves
  // them; anything entered by an admin (MANUAL/AI_SEARCH) is irrelevant
  // here since the public pages only ever show SELF_SUBMITTED records.
  isPublished: boolean("is_published").notNull().default(true),
  // A manual staff signal that this listing has been checked (real club,
  // real contact) -- shown as a badge on the public site to build trust
  // in a brand-new marketplace with no reputation history yet.
  isVerified: boolean("is_verified").notNull().default(false),
  // Self-serve portal login (see src/lib/auth/portal.ts). Null until the
  // club sets a password -- either at self-sign-up time or later via
  // "claim this listing" on their public profile page.
  passwordHash: text("password_hash"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// A specific playing position / vacancy a club is looking to fill.
export const positionNeeds = pgTable("position_needs", {
  id: id(),
  clubId: text("club_id")
    .notNull()
    .references(() => clubs.id, { onDelete: "cascade" }),
  position: text("position").notNull(), // e.g. "Loosehead prop", "Fly-half"
  level: playerLevelEnum("level"),
  notes: text("notes"),
  openSince: timestamp("open_since").notNull().defaultNow(),
  filled: boolean("filled").notNull().default(false),
});

export const players = pgTable("players", {
  id: id(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email"),
  phone: text("phone"),
  nationality: text("nationality"),
  currentCountry: text("current_country"),
  position: text("position").notNull(), // primary playing position
  secondaryPosition: text("secondary_position"),
  // Headshot, uploaded by an admin via Vercel Blob. Shown on the public
  // player card and profile page; null shows a plain initials fallback.
  photoUrl: text("photo_url"),
  level: playerLevelEnum("level"),
  currentClub: text("current_club"), // free-text, may not be in our clubs table
  yearsExperience: integer("years_experience"),
  highlightUrl: text("highlight_url"), // link to highlight reel / stats profile
  notes: text("notes"),
  status: recordStatusEnum("status").notNull().default("NEW"),
  source: sourceTypeEnum("source").notNull().default("MANUAL"),
  sourceDetail: text("source_detail"),
  needsAccommodation: boolean("needs_accommodation").notNull().default(false),
  // See the matching comment on clubs.isPublished above.
  isPublished: boolean("is_published").notNull().default(true),
  // See the matching comment on clubs.isVerified above.
  isVerified: boolean("is_verified").notNull().default(false),
  // See the matching comment on clubs.passwordHash above.
  passwordHash: text("password_hash"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Coaches -- the third marketplace persona alongside clubs and players.
// Deliberately mirrors the players table's shape (status/source/publish/
// verify/portal-login all work identically) rather than introducing a
// different pattern for one entity type.
export const coaches = pgTable("coaches", {
  id: id(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email"),
  phone: text("phone"),
  nationality: text("nationality"),
  currentCountry: text("current_country"),
  specialization: text("specialization").notNull(), // e.g. "Head coach", "Forwards", "Strength & conditioning"
  coachingLevel: text("coaching_level"), // free text certification, e.g. "World Rugby Level 2"
  currentClub: text("current_club"),
  yearsExperience: integer("years_experience"),
  highlightUrl: text("highlight_url"),
  photoUrl: text("photo_url"),
  notes: text("notes"),
  status: recordStatusEnum("status").notNull().default("NEW"),
  source: sourceTypeEnum("source").notNull().default("MANUAL"),
  sourceDetail: text("source_detail"),
  isPublished: boolean("is_published").notNull().default(true),
  isVerified: boolean("is_verified").notNull().default(false),
  passwordHash: text("password_hash"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ---------- Outreach / CRM tracking ----------

export const contactMethodEnum = pgEnum("contact_method", [
  "EMAIL",
  "PHONE",
  "WHATSAPP",
  "IN_PERSON",
  "OTHER",
]);

export const contactLogs = pgTable("contact_logs", {
  id: id(),
  clubId: text("club_id").references(() => clubs.id, { onDelete: "cascade" }),
  playerId: text("player_id").references(() => players.id, {
    onDelete: "cascade",
  }),
  coachId: text("coach_id").references(() => coaches.id, {
    onDelete: "cascade",
  }),
  adminId: text("admin_id").references(() => adminUsers.id),
  method: contactMethodEnum("method").notNull(),
  summary: text("summary").notNull(),
  contactedAt: timestamp("contacted_at").notNull().defaultNow(),
});

// ---------- Matching ----------

export const placementStatusEnum = pgEnum("placement_status", [
  "PROPOSED",
  "CONFIRMED",
  "FELL_THROUGH",
]);

export const placements = pgTable("placements", {
  id: id(),
  clubId: text("club_id")
    .notNull()
    .references(() => clubs.id, { onDelete: "cascade" }),
  playerId: text("player_id")
    .notNull()
    .references(() => players.id, { onDelete: "cascade" }),
  status: placementStatusEnum("status").notNull().default("PROPOSED"),
  startDate: timestamp("start_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ---------- Support services (accommodation) ----------

export const accommodationStatusEnum = pgEnum("accommodation_status", [
  "REQUESTED",
  "SEARCHING",
  "OPTIONS_SENT",
  "BOOKED",
  "NOT_NEEDED",
]);

export const accommodationRequests = pgTable("accommodation_requests", {
  id: id(),
  playerId: text("player_id")
    .notNull()
    .references(() => players.id, { onDelete: "cascade" }),
  placementId: text("placement_id").references(() => placements.id),
  city: text("city"),
  moveInDate: timestamp("move_in_date"),
  budgetNote: text("budget_note"), // free text, e.g. "client covers up to a set monthly amount"
  status: accommodationStatusEnum("status").notNull().default("REQUESTED"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ---------- Spam / abuse mitigation ----------

// One row per public-form submission attempt, keyed by a hashed IP address
// (never the raw IP) and which form was hit. Used to rate-limit the public
// sign-up and inquiry forms; old rows are pruned opportunistically by the
// rate-limit check itself rather than needing a separate cron job.
export const rateLimitEvents = pgTable("rate_limit_events", {
  id: id(),
  ipHash: text("ip_hash").notNull(),
  formType: text("form_type").notNull(), // e.g. "player_application"
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ---------- AI-assisted sourcing ----------

export const searchTargetTypeEnum = pgEnum("search_target_type", [
  "CLUB",
  "PLAYER",
  "COACH",
]);

export const suggestionReviewStatusEnum = pgEnum("suggestion_review_status", [
  "PENDING",
  "ACCEPTED",
  "REJECTED",
]);

// A single run of the AI-assisted search tool.
export const sourcingSearches = pgTable("sourcing_searches", {
  id: id(),
  targetType: searchTargetTypeEnum("target_type").notNull(),
  query: text("query").notNull(), // the admin's natural-language brief
  runByEmail: text("run_by_email"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// One candidate club/player produced by a sourcing search, pending admin review.
export const sourcingSuggestions = pgTable("sourcing_suggestions", {
  id: id(),
  searchId: text("search_id")
    .notNull()
    .references(() => sourcingSearches.id, { onDelete: "cascade" }),
  targetType: searchTargetTypeEnum("target_type").notNull(),
  name: text("name").notNull(),
  summary: text("summary").notNull(), // AI-generated summary of why this looks like a fit
  sourceUrl: text("source_url"), // where the AI found this, for admin to verify
  rawData: jsonb("raw_data"), // structured fields the AI extracted
  reviewStatus: suggestionReviewStatusEnum("review_status")
    .notNull()
    .default("PENDING"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  // set once an admin accepts the suggestion and turns it into a real record
  promotedClubId: text("promoted_club_id"),
  promotedPlayerId: text("promoted_player_id"),
  promotedCoachId: text("promoted_coach_id"),
});

// ---------- Email outreach templates ----------

// Reusable drafts an admin can send from a club/player's row with one
// click. Uses {{variableName}} placeholders (see src/lib/email-templates.ts
// for the render logic and the list of variables available per target
// type), filled in per-recipient in the compose modal before the admin
// opens their email client -- nothing is ever sent server-side.
export const emailTemplates = pgTable("email_templates", {
  id: id(),
  targetType: searchTargetTypeEnum("target_type").notNull(),
  name: text("name").notNull(),
  subject: text("subject").notNull(),
  body: text("body").notNull(),
  // The template pre-selected by default when an admin clicks "Email" on a
  // club/player of this targetType. At most one template per targetType
  // should have this set -- enforced in the server action, not the DB.
  isDefault: boolean("is_default").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ---------- Public marketing content (admin-editable) ----------

// Pricing tiers shown on the public /pricing page. Seeded with placeholder
// numbers -- editable from /admin/settings/pricing whenever a real pricing
// model is decided.
export const pricingPlans = pgTable("pricing_plans", {
  id: id(),
  name: text("name").notNull(),
  priceLabel: text("price_label").notNull(), // free-text so "Free" / "$49" / "Custom" all work
  billingPeriod: text("billing_period"), // e.g. "per month" -- null reads as one-time/custom
  tagline: text("tagline"),
  features: jsonb("features").notNull().default([]), // string[]
  isFeatured: boolean("is_featured").notNull().default(false),
  sortOrder: integer("sort_order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Quote cards shown on the public site. Seeded with clearly-placeholder
// (Latin filler) text -- there isn't real customer volume yet to draw
// genuine testimonials from. Editable from /admin/settings/testimonials so
// real ones can replace them later.
export const testimonials = pgTable("testimonials", {
  id: id(),
  quote: text("quote").notNull(),
  authorName: text("author_name").notNull(),
  authorRole: text("author_role"),
  sortOrder: integer("sort_order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// General "contact us" messages from the public site (not tied to any
// specific club/player/coach listing -- those go through contactLogs via
// submitInquiry instead). Reviewed from /admin/messages.
export const contactMessages = pgTable("contact_messages", {
  id: id(),
  name: text("name").notNull(),
  email: text("email").notNull(),
  message: text("message").notNull(),
  isRead: boolean("is_read").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ---------- Portal accounts & messaging ----------

// A club, player, or coach's own self-serve login is just that record's
// row (see passwordHash on each table) -- there's no separate "users"
// table. This enum is only for tagging *which* table a portal session or
// a message party refers to.
export const accountTypeEnum = pgEnum("account_type", [
  "CLUB",
  "PLAYER",
  "COACH",
]);

// One conversation thread between two portal accounts (a club and a
// player, say). Deliberately not a foreign key to clubs/players/coaches
// directly -- each party can be any of the three tables, so the type+id
// pair is resolved in application code (src/lib/portal-messaging.ts).
export const conversations = pgTable("conversations", {
  id: id(),
  partyAType: accountTypeEnum("party_a_type").notNull(),
  partyAId: text("party_a_id").notNull(),
  partyBType: accountTypeEnum("party_b_type").notNull(),
  partyBId: text("party_b_id").notNull(),
  lastMessageAt: timestamp("last_message_at").notNull().defaultNow(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const messages = pgTable("messages", {
  id: id(),
  conversationId: text("conversation_id")
    .notNull()
    .references(() => conversations.id, { onDelete: "cascade" }),
  senderType: accountTypeEnum("sender_type").notNull(),
  senderId: text("sender_id").notNull(),
  body: text("body").notNull(),
  readAt: timestamp("read_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ---------- Relations (for Drizzle's relational query API) ----------

export const clubsRelations = relations(clubs, ({ many }) => ({
  positionNeeds: many(positionNeeds),
  contactLogs: many(contactLogs),
  placements: many(placements),
}));

export const playersRelations = relations(players, ({ many }) => ({
  contactLogs: many(contactLogs),
  placements: many(placements),
  accommodationRequests: many(accommodationRequests),
}));

export const coachesRelations = relations(coaches, ({ many }) => ({
  contactLogs: many(contactLogs),
}));

export const conversationsRelations = relations(conversations, ({ many }) => ({
  messages: many(messages),
}));

export const messagesRelations = relations(messages, ({ one }) => ({
  conversation: one(conversations, {
    fields: [messages.conversationId],
    references: [conversations.id],
  }),
}));

export const placementsRelations = relations(placements, ({ one, many }) => ({
  club: one(clubs, { fields: [placements.clubId], references: [clubs.id] }),
  player: one(players, {
    fields: [placements.playerId],
    references: [players.id],
  }),
  accommodationRequests: many(accommodationRequests),
}));

export const sourcingSearchesRelations = relations(
  sourcingSearches,
  ({ many }) => ({
    suggestions: many(sourcingSuggestions),
  }),
);

export const sourcingSuggestionsRelations = relations(
  sourcingSuggestions,
  ({ one }) => ({
    search: one(sourcingSearches, {
      fields: [sourcingSuggestions.searchId],
      references: [sourcingSearches.id],
    }),
  }),
);
